@BaseAddress = http://localhost:5247
@CourseId = 3fa85f64-5717-6562-b3fc-2c963f66afa6
Post {{BaseAddress}}/api/v1/basket/item
Accept : application/json
Content-Type: application/json
{
  "courseId": "3fa85f64-5537-6562-b3fc-2c963f66afa6",
  "courseName": "xxx8",
  "coursePrice": 13
 
}
###

DELETE {{BaseAddress}}/api/v1/basket/item/{{CourseId}}
Accept: application/json
###

GET {{BaseAddress}}/api/v1/basket
Accept: application/json
###
PUT {{BaseAddress}}/api/v1/basket/apply-discount-coupon
Accept : application/json
Content-Type: application/json
{
  "coupon" : "asdfbc",
  "rate" : 0.25
 
}
###
DELETE {{BaseAddress}}/api/v1/basket/remove-discount-coupon
Accept: application/json
