@BaseAddress = http://localhost:5184
@CategoryId = 08dde3ad-0515-11f2-0005-9a3c7a000000
@CourseId = 08dde421-f478-3bcf-0250-f272b6050000
GET {{BaseAddress}}/api/v1/categories
Accept: application/json

###
Post {{BaseAddress}}/api/v1/categories
Accept : application/json
Content-Type: application/json
{
    "name": "New Category"
}
###

GET {{BaseAddress}}/api/v1/categories/{{CategoryId}}
Accept: application/json
###

POST {{BaseAddress}}/api/v1/courses
Accept : application/json
Content-Type: application/json
{
    "name": "New Course 3",
    "description": "Course Description",
    "categoryId": "{{CategoryId}}",
    "imageUrl": "https://example.com/image.png",
    "price": 99.99  
    
}
###
GET {{BaseAddress}}/api/v1/courses
Accept: application/json

###
GET {{BaseAddress}}/api/v1/courses/{{CourseId}}
Accept: application/json
###

PUT {{BaseAddress}}/api/v1/courses
Accept : application/json
Content-Type: application/json
{
    "id": "{{CourseId}}",
    "name": "Updated Course Name",
    "description": "Updated Description",
    "categoryId": "{{CategoryId}}",
    "imageUrl": "https://example.com/updated-image.png",
    "price": 79.99  
}

###
DELETE {{BaseAddress}}/api/v1/courses/{{CourseId}}
Accept: application/json
###