@BaseAddress = http://localhost:5184
@CategoryId = 08dde3ad-0515-11f2-0005-9a3c7a000000
GET {{BaseAddress}}/api/categories
Accept: application/json

###
Post {{BaseAddress}}/api/categories
Accept : application/json
Content-Type: application/json
{
    "name": "New Category"
}
###

GET {{BaseAddress}}/api/categories/{{CategoryId}}
Accept: application/json
###

POST {{BaseAddress}}/api/courses
Accept : application/json
Content-Type: application/json
{
    "name": "New Course 3",
    "description": "Course Description",
    "categoryId": "{{CategoryId}}",
    "imageUrl": "https://example.com/image.png",
    "price": 99.99  
    
}
###
GET {{BaseAddress}}/api/courses
Accept: application/json